# actuator 配置参数
management:
  endpoint:
    shutdown:
      enabled: false   # 禁用接口关闭 Spring Boot
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"        # 打开所有的监控点
        exclude: shutdown   # 禁用关机服务
      base-path: /actuator  # 定制监控点路径，默认为 /actuator
# 定制 actuator 信息
info:
  app:
    name: ferry
    author: ferry
    email: ferry_sy@163.com
    desciption: 人生而自由，却无往不在枷锁之中



logging:
  level:
    root: DEBUG
